name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run linter
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Login to Yandex Container Registry
      run: |
        echo ${{ secrets.YC_SA_JSON_CREDENTIALS }} | docker login --username json_key --password-stdin cr.yandex
        
    - name: Build and push Docker image
      run: |
        docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }} .
        docker tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }} cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest
        
    - name: Create git tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ inputs.version }}
        git push origin ${{ inputs.version }}
        
    - name: Update CHANGELOG
      run: |
        echo "# ${{ inputs.version }} - $(date '+%Y-%m-%d')" > CHANGELOG_NEW.md
        echo "" >> CHANGELOG_NEW.md
        git log --oneline $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD >> CHANGELOG_NEW.md
        echo "" >> CHANGELOG_NEW.md
        cat CHANGELOG.md >> CHANGELOG_NEW.md
        mv CHANGELOG_NEW.md CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG for version ${{ inputs.version }}"
        git push
        
    - name: Create issue
      run: |
        gh issue create --title "Release ${{ inputs.version }}" --body "Релиз версии ${{ inputs.version }} создан $(date '+%Y-%m-%d %H:%M:%S'). Автор: ${{ github.actor }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}